---
title: "Approximation of the Binomial probabilities in R"
author: "Ivan Gercev"
date: "06 April 2021"
subtitle: "COMPUTER PRACTICE 2"
output: 
  pdf_document: default
  html_notebook: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

git repository: https://github.com/foxybbb/TSI_Probability-Statistics

## Include functions for Bernoulli formula and Normal and Poisson approximation from learning-by-doing materials 03.

```{r}
bernoulliTrialCalc = function(k,n.p){
return (dbinom(k, n,p))
}
```


```{r}
approxMoivreLaplaceLocal = function(k, n, p){
	x = (k - n*p)/sqrt(n*p*(1-p))
	# Call the normal density function
  fi = dnorm(x)
	# Approximate calculation
	p = fi/sqrt(n*p*(1-p))
	return(p)
}
```

## Define a function, which implements proper formula selection, following the last diagram in Topic 1.5 lecture slides.
```{r}
ProbabilityApproximate = function (k,n,p)
{
  if(n > 20){
    return (approxMoivreLaplaceLocal(k,n,p))
  }
  else{
    return (bernoulliTrialCalc(k,n,p))
  }
}
```
