---
title: "COMPUTER PRACTICE 4.Exploratory  data analysis in R"
author: "Ivan Gercev"
date: "06 April 2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
  html_notebook: default
subtitle: COMPUTER PRACTICE 4
---
```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.height=4) 

```
# Data processing
## installing the requirements
```{r echo=FALSE}
packages <- c("qcc", "dplyr", "tidyr","knitr","plyr")
install.packages(setdiff(packages, rownames(installed.packages()))) 

library(qcc)
library(rlang)
library(dplyr)
library(tidyr) 

```

## Data downloading from the source
```{r echo=FALSE}


if (!file.exists("wine_data.csv")) {
  id <- "17SRO5g0Ho1GWHFwfYtYSoMlGlMJBdd7o" # google file ID
  
  download.file(
    sprintf("https://docs.google.com/uc?id=%s&export=download", id),
    destfile = "wine_data.csv",
    noprogress = TRUE
  )
  
}
 
```
## Read data set file

```{r}
wine_data <- read.csv("wine_data.csv",header=T ,sep = ",")
kable(head(wine_data), caption ="Chess players")
```

# Descriptive statistics 
```{r}
kable(summary(wine_data), caption ="Summary statistics")

```
```{r}
samplesAmount = nrow(wine_data)
samplesAmount
```
Number of samples `r samplesAmount`

# Descriptive statistics for points of age of chess players
```{r}
df = data.frame(unclass(summary(wine_data$points)))
colnames(df)<-c("points")
kable(df,caption ="5-number statistics (Age)")

```
```{r}
plot(ecdf(wine_data$points), main="Empirical cumulative distribution function (Age)")
```
```{r}
kable(table(wine_data$points),caption ="Absolute frequencies (Age)")

```

```{r}

hist(wine_data$points, main="Histogram (Age)")

```
```{r}
wj = table(wine_data$points)/samplesAmount
kable(round(wj, digits=3),caption ="Relative frequencies (Age)")

```

```{r}

plot(ecdf(wine_data$points), main="Empirical cumulative distribution function (Age)")

plot(wj, type="b", main="Distribution (Age)")

boxplot(wine_data$points, main="Box-and-whisker plot (Age)")

```



```{r}

barplot(wine_data$points,xlab="player ages") 
# Display the 5 largest countries by number of samples
nwj = table(wine_data$country)/samplesAmount
pie(round(tail(sort(nwj),5),digits = 1),radius = 1)

pareto.chart(wj/samplesAmount, main="Pareto Chart")




```

```{r}
plot(wine_data$price,wine_data$points, main="Scatterplot",
   xlab="Wine price", ylab="Wine points", pch=19,col = "green") 

```

```{r}

table(wine_data$country, wine_data$points,dnn = c("countries","points"))
```

