---
title: "Untitled"
author: "Ivans Gercevs"
date: "18 05 2021"
output:
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

## lecture practise
```{r}
population <- round(rnorm(1000,175,12))
population 
eX <- mean(population)
sdX <-sqrt(sum(population-mean(population)^2)/length(population))

eX
sdX
hist(population)

```



## Monte-carlo
```{r }
n = 10
meanArray <- c()
sdArray <- c()
for (i in 1:20){
  sampl <- sample(population, n)
  Xmean <- mean(sampl)
  Xsd <- sqrt(sum((sampl - mean(sampl)) ^ 2) / n)
meanArray <- append(meanArray, Xmean)
sdArray <- append(sdArray, Xsd)
}
meanArray
mean(meanArray)
hist(meanArray)
sdArray

mean(sdArray)
hist(sdArray)

```

# learning by doing

```{r}
x <- sdArray

plot(x, dchisq(x, 3), type="l", xlab="x", ylab="f(x)", col="red", 
     main="Chi-square: probability density function")
lines(x, dchisq(x, 5), col="green")
lines(x, dchisq(x, 10), col="blue")
```


## Student distribution
```{r}
x <- seq(-4,4,length=10010)

plot(x, dt(x, 10), type="l", xlab="x", ylab="f(x)", col="blue",
     main="Student distribution: probability density function")
lines(x, dt(x, 3), col="green")
lines(x, dt(x, 1), col="red")
```


### Convergence of the Student distribution to the Normal distribution for large degree of freedom
```{r}
gamma = 0.95
level = (1+gamma)/2
x <- seq(2, 150)

plot(x, qt(level,x), type="l", xlab="Degrees of freedom", ylab="95% quantile", 
     col="blue",
     main="Student distribution's quantiles")
# Normal quantile
lines(x, rep(qnorm(level),length(x)), col="red")
```

# Confidence intervals


## Graphical illustation of confidence intervals for normally distributed estimates
```{r}

x <- seq(-4,4,length=100)

# Quantiles for 95% confidence interval (2.5% and 97.5% quantiles)
gamma = 0.95
q1=qnorm((1-gamma)/2)
q2=qnorm((1+gamma)/2)

```


```{r}
hx <- dnorm(x)
plot(x, hx, type="l", xlab="x", ylab="f(x)",
     main="Normal PDF")
polygon(c(q1,x[q1 <= x & x  <= q2],q2), c(0,hx[q1 <=x & x <= q2],0),
        col="lightgray") 
```

